"""add current_node_id to ChatSession

Revision ID: 044133911ca9
Revises: 89728c98f559
Create Date: 2025-08-29 15:09:21.774012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044133911ca9'
down_revision: Union[str, None] = '89728c98f559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('current_node_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'current_node_id')
    # ### end Alembic commands ###
