"""Add last_node_id to ChatSession

Revision ID: 13418c9dba4e
Revises: 1ceae7cdd896
Create Date: 2025-08-30 05:38:49.763081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13418c9dba4e'
down_revision: Union[str, None] = '1ceae7cdd896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('last_node_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'last_node_id')
    # ### end Alembic commands ###
