"""add current_node_id to ChatSession

Revision ID: 1ceae7cdd896
Revises: 044133911ca9
Create Date: 2025-08-29 15:25:05.693569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ceae7cdd896'
down_revision: Union[str, None] = '044133911ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'current_node_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('current_node_id', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
