"""Add flow_json to widgets

Revision ID: 89728c98f559
Revises: d271834e5f15
Create Date: 2025-08-13 11:16:02.039556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89728c98f559'
down_revision: Union[str, None] = 'd271834e5f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('flow_json', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'flow_json')
    # ### end Alembic commands ###
