"""add current_node_id to ChatSession

Revision ID: 98230a7f8f24
Revises: 13418c9dba4e
Create Date: 2025-08-30 06:12:55.440173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98230a7f8f24'
down_revision: Union[str, None] = '13418c9dba4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('current_node_id', sa.String(length=100), nullable=True))
    op.drop_column('chat_sessions', 'last_node_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('last_node_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('chat_sessions', 'current_node_id')
    # ### end Alembic commands ###
