"""Add ai_website_id field

Revision ID: d271834e5f15
Revises: ed892cf8f166
Create Date: 2025-08-08 04:49:49.212551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd271834e5f15'
down_revision: Union[str, None] = 'ed892cf8f166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('ai_website_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'ai_website_id')
    # ### end Alembic commands ###
