"""Change instruction_text to Text

Revision ID: dfa36f146029
Revises: e21d40fc523c
Create Date: 2025-11-05 12:15:07.782235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfa36f146029'
down_revision: Union[str, None] = 'e21d40fc523c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widget_indexes', 'instruction_text',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widget_indexes', 'instruction_text',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
