"""add widget_indexes table

Revision ID: e21d40fc523c
Revises: 98230a7f8f24
Create Date: 2025-09-26 09:13:22.882071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21d40fc523c'
down_revision: Union[str, None] = '98230a7f8f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_indexes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('instruction_text', sa.String(length=255), nullable=False),
    sa.Column('index_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_indexes')
    # ### end Alembic commands ###
