"""Initial clean migration

Revision ID: ed892cf8f166
Revises: 
Create Date: 2025-07-16 13:51:05.645631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed892cf8f166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('api_pass', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='clusterstatustype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_name', sa.String(length=255), nullable=False),
    sa.Column('component_css', sa.Text(), nullable=True),
    sa.Column('component_html', sa.Text(), nullable=True),
    sa.Column('component_js', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('personal', 'business', name='organisationtype'), nullable=True),
    sa.Column('organization_name', sa.String(length=80), nullable=True),
    sa.Column('vat_or_gst_in', sa.String(length=255), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currencytype'), nullable=True),
    sa.Column('kyc_finish_timestamp', sa.DateTime(), nullable=True),
    sa.Column('kyc_verified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_index(op.f('ix_organisations_organization_name'), 'organisations', ['organization_name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('domain', 'vm', 'rds', 'hosting', 'license', 'email', 'bare_metal_server', 'web_builder', name='productcategory'), nullable=False),
    sa.Column('product_details', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('server_common_addons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addon_type', sa.Enum('License', 'Support', 'OS'), nullable=False),
    sa.Column('addon_name', sa.String(length=100), nullable=False),
    sa.Column('price_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('billing_period', sa.Enum('monthly', 'annual', 'one_time', 'triannual', 'same_as_main', name='billingperiod'), nullable=False),
    sa.Column('applicable_to', sa.Enum('VM', 'Dedicated Server', 'All'), nullable=False),
    sa.Column('applicable_os', sa.Enum('Linux', 'Windows_Server', 'All', name='applicableos'), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('version_name', sa.String(length=255), nullable=True),
    sa.Column('is_inclusive', sa.Boolean(), nullable=True),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('webhookoutputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_account_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('error_description', sa.String(length=1024), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhookoutputs_id'), 'webhookoutputs', ['id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_ref', sa.String(length=25), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('invoice_title', sa.String(length=255), nullable=False),
    sa.Column('inv_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currencytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('meta_data', mysql.JSON(), nullable=True),
    sa.Column('payment_mode', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dedicated_server_addons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('addon_type', sa.Enum('RAM', 'Storage'), nullable=False),
    sa.Column('addon_ram_gb', sa.Integer(), nullable=True),
    sa.Column('ram_price_inr', sa.Integer(), nullable=True),
    sa.Column('ram_price_usd', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.Enum('SSD', 'HDD', 'NVMe'), nullable=True),
    sa.Column('addon_storage_gb', sa.Integer(), nullable=True),
    sa.Column('storage_price_inr', sa.Integer(), nullable=True),
    sa.Column('storage_price_usd', sa.Integer(), nullable=True),
    sa.Column('alpha_3_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dedicated_server_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('configuration_type', sa.Enum('fixed', 'customizable', name='configurationtype'), nullable=False),
    sa.Column('storage_type', sa.Enum('SSD', 'HDD', 'NVMe', 'SSD_HDD', name='storagetype'), nullable=False),
    sa.Column('base_ram_gb', sa.Integer(), nullable=False),
    sa.Column('base_storage_gb', sa.Integer(), nullable=False),
    sa.Column('nvme_slots', sa.Integer(), nullable=True),
    sa.Column('ssd_hdd_slots', sa.Integer(), nullable=True),
    sa.Column('applicable_os', sa.Enum('Linux', 'Windows_Server', 'All', name='applicableos'), nullable=False),
    sa.Column('register_inr', sa.Integer(), nullable=False),
    sa.Column('renew_inr', sa.Integer(), nullable=False),
    sa.Column('os_cost_inr', sa.Integer(), nullable=True),
    sa.Column('register_usd', sa.Integer(), nullable=False),
    sa.Column('renew_usd', sa.Integer(), nullable=False),
    sa.Column('promo_inr', sa.Integer(), nullable=True),
    sa.Column('promo_usd', sa.Integer(), nullable=True),
    sa.Column('upfront_annual_discount', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('upfront_triannual_discount', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('min_period', sa.Integer(), nullable=False),
    sa.Column('max_period', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('delivery_time', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedicated_server_prices_id'), 'dedicated_server_prices', ['id'], unique=False)
    op.create_table('domain_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tld', sa.String(length=25), nullable=False),
    sa.Column('register_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('transfer_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('restore_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('register_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('transfer_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('restore_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('min_period', sa.Integer(), nullable=True),
    sa.Column('max_period', sa.Integer(), nullable=True),
    sa.Column('promo_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('promo_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('special_first_year_price_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('special_first_year_price_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('minimum_year_for_promo_price', sa.Integer(), nullable=True),
    sa.Column('privacy_eligible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosting_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('bandwidth_gb', sa.Integer(), nullable=False),
    sa.Column('account_limit', sa.Integer(), nullable=False),
    sa.Column('applicable_os', sa.Enum('Linux', 'Windows_Server', 'All', name='applicableos'), nullable=False),
    sa.Column('annual_register_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('annual_renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('annual_register_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('annual_renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('promo_inr', sa.Integer(), nullable=True),
    sa.Column('promo_usd', sa.Integer(), nullable=True),
    sa.Column('upfront_biannual_discount_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_biannual_discount_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_triannual_discount_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_triannual_discount_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_biannual_renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_biannual_renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_triannual_renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_triannual_renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('min_period', sa.Integer(), nullable=False),
    sa.Column('max_period', sa.Integer(), nullable=False),
    sa.Column('features', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_database_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('vcpu_count', sa.Integer(), nullable=False),
    sa.Column('base_ram_gb', sa.Integer(), nullable=False),
    sa.Column('base_disk_gb', sa.Integer(), nullable=False),
    sa.Column('applicable_os', sa.Enum('Linux', 'Windows_Server', 'All', name='applicableos'), nullable=True),
    sa.Column('database_type', sa.Enum('PostgreSQL', 'MySQL', name='databasecategory'), nullable=False),
    sa.Column('register_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('register_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('promo_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('promo_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_annual_discount_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_annual_discount_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_annual_renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_annual_renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_period', sa.Integer(), nullable=False),
    sa.Column('max_period', sa.Integer(), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=False),
    sa.Column('location_country', sa.String(length=100), nullable=False),
    sa.Column('location_continent', sa.String(length=100), nullable=False),
    sa.Column('delivery_time', sa.String(length=50), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_database_prices_id'), 'managed_database_prices', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('first_purchase_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currency_enum'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('Yearly', 'Monthly', 'Quarterly', 'Semi_Annually', 'Bi_Annually', 'Tri_Annually', name='orderbillingcycleperiod'), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Suspended', 'Terminated', 'Creating', 'Transferring', 'TransferFailed', 'Expired', name='orderstatustype'), nullable=False),
    sa.Column('next_renewal', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('edit', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'service_id', name='uq_role_service')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('subscription_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('max_accounts', sa.Integer(), nullable=False),
    sa.Column('register_inr', sa.Integer(), nullable=False),
    sa.Column('renew_inr', sa.Integer(), nullable=False),
    sa.Column('register_usd', sa.Integer(), nullable=False),
    sa.Column('renew_usd', sa.Integer(), nullable=False),
    sa.Column('promo_inr', sa.Integer(), nullable=True),
    sa.Column('min_period', sa.Integer(), nullable=False),
    sa.Column('max_period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=170), nullable=True),
    sa.Column('telephone_number', sa.String(length=25), nullable=True),
    sa.Column('hashed_password', sa.String(length=150), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=120), nullable=True),
    sa.Column('oauth_uid', sa.String(length=150), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('password_provider', sa.String(length=80), nullable=True),
    sa.Column('is_group_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('telephone_number'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('vm_addons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('addon_type', sa.Enum('RAM', 'Disk', name='addontype'), nullable=False),
    sa.Column('addon_name', sa.String(length=100), nullable=False),
    sa.Column('addon_unit_size', sa.Integer(), nullable=True),
    sa.Column('price_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('billing_period', sa.Enum('monthly', 'annual', 'one_time', 'triannual', 'same_as_main', name='billingperiod'), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('alpha_3_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_addons_id'), 'vm_addons', ['id'], unique=False)
    op.create_table('vm_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('vcpu_count', sa.Integer(), nullable=False),
    sa.Column('base_ram_gb', sa.Integer(), nullable=False),
    sa.Column('base_disk_gb', sa.Integer(), nullable=False),
    sa.Column('max_ram_gb', sa.Integer(), nullable=False),
    sa.Column('plid', sa.Integer(), nullable=True),
    sa.Column('applicable_os', sa.Enum('Linux', 'Windows_Server', 'All', name='applicableos'), nullable=False),
    sa.Column('register_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('register_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('promo_inr', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('promo_usd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('upfront_annual_discount_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_annual_discount_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_biannual_discount_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_biannual_discount_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_annual_renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_annual_renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_biannual_renew_inr', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('upfront_biannual_renew_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_period', sa.Integer(), nullable=False),
    sa.Column('max_period', sa.Integer(), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=False),
    sa.Column('location_country', sa.String(length=100), nullable=False),
    sa.Column('location_continent', sa.String(length=100), nullable=False),
    sa.Column('delivery_time', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_prices_id'), 'vm_prices', ['id'], unique=False)
    op.create_table('access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1050), nullable=False),
    sa.Column('user_uuid', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_tokens_id'), 'access_tokens', ['id'], unique=False)
    op.create_table('bare_metal_server_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('srv_hostname', sa.String(length=255), nullable=False),
    sa.Column('srv_ip_address', sa.String(length=45), nullable=True),
    sa.Column('srv_cpu', sa.String(length=30), nullable=True),
    sa.Column('srv_ram_gb', sa.Integer(), nullable=False),
    sa.Column('srv_refid', sa.String(length=100), nullable=True),
    sa.Column('srv_status', sa.Enum('creating', 'starting', 'running', 'stopping', 'stopped', 'reinstalling', name='baremetalserverstatustype'), nullable=False),
    sa.Column('srv_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('os_name', sa.String(length=255), nullable=False),
    sa.Column('friendly_srvname', sa.String(length=80), nullable=True),
    sa.Column('ipv6_enabled', sa.Boolean(), nullable=True),
    sa.Column('ipv6_address', sa.String(length=255), nullable=True),
    sa.Column('ddos_enabled', sa.Boolean(), nullable=True),
    sa.Column('ddos_pps', sa.String(length=30), nullable=True),
    sa.Column('srv_location', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id')
    )
    op.create_table('billing_invoice_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_title', sa.String(length=300), nullable=False),
    sa.Column('discount_percentage', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currencytype'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('next_renewal', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('billing_invoice_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billing_invoice_id'], ['billing_invoices.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_handles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('telephone_number', sa.String(length=25), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('organisation_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_handles_id'), 'domain_handles', ['id'], unique=False)
    op.create_table('email_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('next_renewal', sa.DateTime(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('mx_records', mysql.JSON(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id')
    )
    op.create_table('hosting_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('next_renewal', sa.DateTime(), nullable=False),
    sa.Column('name_servers', mysql.JSON(), nullable=True),
    sa.Column('controlpanel_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id')
    )
    op.create_table('kyc_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('user_uuid', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_files_id'), 'kyc_files', ['id'], unique=False)
    op.create_table('login_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('verified_device', sa.Boolean(), nullable=True),
    sa.Column('login_time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_details_id'), 'login_details', ['id'], unique=False)
    op.create_table('managed_database_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('vcpu_count', sa.Integer(), nullable=False),
    sa.Column('base_ram_gb', sa.Integer(), nullable=False),
    sa.Column('base_disk_gb', sa.Integer(), nullable=False),
    sa.Column('current_ram_gb', sa.Integer(), nullable=False),
    sa.Column('current_disk_gb', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('creating', 'starting', 'running', 'stopping', 'stopped', 'reinstalling', name='manageddatabasestatustype'), nullable=False),
    sa.Column('database_type', sa.Enum('PostgreSQL', 'MySQL', name='databasecategory'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('ipv6_enabled', sa.Boolean(), nullable=True),
    sa.Column('ipv6_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id')
    )
    op.create_table('order_bundles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id_1', sa.Integer(), nullable=False),
    sa.Column('order_id_2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id_1'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['order_id_2'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1050), nullable=False),
    sa.Column('user_uuid', sa.String(length=40), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('billing_invoice_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.Enum('INR', 'USD', 'EUR', name='currencytype'), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('transaction_type', sa.Enum('credit', 'debit', name='transactiontype'), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'pending', name='transactionstatustype'), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('domain_renewal', 'user_add_fund', 'order_renewal', 'vm_order', 'domain_order', 'hosting_order', 'domain_transfer', 'rds_transfer', name='transactioncategorytype'), nullable=False),
    sa.ForeignKeyConstraint(['billing_invoice_id'], ['billing_invoices.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('user_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('verification_code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.Enum('forgot_password', 'multi_factor', name='verificationcodetype'), nullable=False),
    sa.Column('auth_token', sa.String(length=255), nullable=False),
    sa.Column('attempt_counter', sa.Integer(), nullable=False),
    sa.Column('resend_counter', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_verification_codes_id'), 'user_verification_codes', ['id'], unique=False)
    op.create_table('vm_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('vm_number', sa.String(length=10), nullable=True),
    sa.Column('vm_name', sa.String(length=255), nullable=False),
    sa.Column('vm_hostname', sa.String(length=255), nullable=False),
    sa.Column('vm_ip_address', sa.String(length=45), nullable=True),
    sa.Column('vm_cluster_id', sa.Integer(), nullable=True),
    sa.Column('vcpu_count', sa.Integer(), nullable=False),
    sa.Column('base_ram_gb', sa.Integer(), nullable=False),
    sa.Column('base_disk_gb', sa.Integer(), nullable=False),
    sa.Column('current_ram_gb', sa.Integer(), nullable=False),
    sa.Column('current_disk_gb', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('vps_name', sa.String(length=80), nullable=True),
    sa.Column('vm_status', sa.Enum('creating', 'starting', 'running', 'stopping', 'stopped', 'reinstalling', name='virtualmachinestatustype'), nullable=False),
    sa.Column('ipv6_enabled', sa.Boolean(), nullable=True),
    sa.Column('ipv6_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['vm_cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('webbuilder_details',
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('launched', sa.Boolean(), nullable=True),
    sa.Column('launched_at', sa.DateTime(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('css_content', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('allowed_domains', mysql.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_token'), 'widgets', ['token'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('action_name', sa.Enum('listvm', 'createvm', 'startvm', 'stopvm', 'restartvm', 'poweroffvm', 'reinstallvm', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'locked', name='actionstatustype'), nullable=True),
    sa.Column('root_pass', sa.String(length=256), nullable=True),
    sa.Column('plid', sa.String(length=256), nullable=True),
    sa.Column('vm_plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vm_order_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_table('aibuilder_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('next_renewal', sa.DateTime(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('webbuilder_uuid', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['webbuilder_uuid'], ['webbuilder_details.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.String(length=255), nullable=False),
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('last_message', sa.String(length=1000), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('domain_order_details',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('privacy', sa.Boolean(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('next_renewal', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('gateway', sa.Boolean(), nullable=True),
    sa.Column('domain_handle_id', sa.Integer(), nullable=True),
    sa.Column('name_servers', mysql.JSON(), nullable=True),
    sa.Column('dhc_order_id', sa.Integer(), nullable=True),
    sa.Column('dns_manage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['domain_handle_id'], ['domain_handles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('vm_addon_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addon_product_name', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('parent_virtual_machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['parent_virtual_machine_id'], ['vm_order_details.id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id', 'parent_virtual_machine_id')
    )
    op.create_table('vm_bandwidth_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('inbound_bytes', sa.BigInteger(), nullable=True),
    sa.Column('outbound_bytes', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('usage_date', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vm_order_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_bandwidth_usage_id'), 'vm_bandwidth_usage', ['id'], unique=False)
    op.create_index(op.f('ix_vm_bandwidth_usage_usage_date'), 'vm_bandwidth_usage', ['usage_date'], unique=False)
    op.create_table('domain_manage_dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_order_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.Enum('A_Record', 'MX_Record', 'CNAME_Record', 'TXT_Record', name='dnsrecordtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.Column('record', sa.String(length=2048), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('ttl >= 7200 AND ttl <= 86400', name='check_ttl_range'),
    sa.ForeignKeyConstraint(['domain_order_id'], ['domain_order_details.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_manage_dns_records_id'), 'domain_manage_dns_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_manage_dns_records_id'), table_name='domain_manage_dns_records')
    op.drop_table('domain_manage_dns_records')
    op.drop_index(op.f('ix_vm_bandwidth_usage_usage_date'), table_name='vm_bandwidth_usage')
    op.drop_index(op.f('ix_vm_bandwidth_usage_id'), table_name='vm_bandwidth_usage')
    op.drop_table('vm_bandwidth_usage')
    op.drop_table('vm_addon_order_details')
    op.drop_table('domain_order_details')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('aibuilder_order_details')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_widgets_token'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_table('webbuilder_details')
    op.drop_table('vm_order_details')
    op.drop_index(op.f('ix_user_verification_codes_id'), table_name='user_verification_codes')
    op.drop_table('user_verification_codes')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('order_bundles')
    op.drop_table('managed_database_order_details')
    op.drop_index(op.f('ix_login_details_id'), table_name='login_details')
    op.drop_table('login_details')
    op.drop_index(op.f('ix_kyc_files_id'), table_name='kyc_files')
    op.drop_table('kyc_files')
    op.drop_table('hosting_order_details')
    op.drop_table('email_order_details')
    op.drop_index(op.f('ix_domain_handles_id'), table_name='domain_handles')
    op.drop_table('domain_handles')
    op.drop_table('billing_invoice_details')
    op.drop_table('bare_metal_server_order_details')
    op.drop_index(op.f('ix_access_tokens_id'), table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index(op.f('ix_vm_prices_id'), table_name='vm_prices')
    op.drop_table('vm_prices')
    op.drop_index(op.f('ix_vm_addons_id'), table_name='vm_addons')
    op.drop_table('vm_addons')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cription_prices')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('orders')
    op.drop_index(op.f('ix_managed_database_prices_id'), table_name='managed_database_prices')
    op.drop_table('managed_database_prices')
    op.drop_table('hosting_prices')
    op.drop_table('domain_prices')
    op.drop_index(op.f('ix_dedicated_server_prices_id'), table_name='dedicated_server_prices')
    op.drop_table('dedicated_server_prices')
    op.drop_table('dedicated_server_addons')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_webhookoutputs_id'), table_name='webhookoutputs')
    op.drop_table('webhookoutputs')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('server_common_addons')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organisations_organization_name'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
